---
sudo: required
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.atspkg
    - /usr/local/lib/ats2-postiats-0.3.8/
    - /usr/local/bin
addons:
  apt:
    packages:
      libgmp3-dev
matrix:
  include:
    - language: python
      addons:
        apt:
          packages:
            - cabal-install-head
            - ghc-8.4.1
            - ghc-8.2.2
          sources:
            - hvr-ghc

before_install:
  - export PATH=/opt/ghc/bin:$PATH
  - cabal update
  - pip install yamllint

script:
  - pip install yamllint
  - yamllint .travis.yml
  - yamllint .stylish-haskell.yaml
  - yamllint .hlint.yaml
  - yamllint .yamllint
  - curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s fast-arithmetic/.atsfmt.toml
  - cd fast-arithmetic
  - cabal new-build
  # - cabal new-build all -w ghc-8.2.2
