---
sudo: required
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.atspkg
addons:
  apt:
    packages:
      libgmp3-dev
matrix:
  include:
    - language: python
      addons:
        apt:
          packages:
            - cabal-install-head
            - ghc-8.4.2
          sources:
            - hvr-ghc

install:
  - export PATH=/opt/ghc/bin:$PATH
  - cabal update
  - pip install yamllint
  - curl -sSl https://raw.githubusercontent.com/vmchale/atspkg/master/bash/install.sh | bash -s
  - atspkg clean

script:
  - pip install yamllint
  - yamllint .travis.yml
  - yamllint .stylish-haskell.yaml
  - yamllint .hlint.yaml
  - yamllint .yamllint
  - curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s fast-arithmetic/.atsfmt.toml
  - cd fast-arithmetic
  # TODO only do this for Linux
  - atspkg build
  - atspkg test
  - cabal new-build
  - cabal new-test
