---
sudo: required
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.atspkg
addons:
  apt:
    packages:
      - libgmp3-dev
      - cabal-install-head
    sources:
      - hvr-ghc
matrix:
  include:
    - language: c
      addons:
        apt:
          packages:
            - ghc-8.4.3
    - language: c
      addons:
        apt:
          packages:
            - ghc-8.2.2
    - language: c
      addons:
        apt:
          packages:
            - ghc-8.0.2
    - language: c
      addons:
        apt:
          packages:
            - ghc-7.10.3
    - language: c
      os: osx

install:
  - |
    if [ `uname` = "Darwin" ]
    then
      brew install cabal-install
    else
      export PATH=/opt/ghc/bin:$PATH
    fi
  - cabal update
  - curl -sSl https://raw.githubusercontent.com/vmchale/atspkg/master/bash/install.sh | bash -s

script:
  - |
    if [ `uname` = "Linux" ]
    then
      curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s fast-arithmetic/.atsfmt.toml
    fi
  - cd fast-arithmetic
  - atspkg build --pkg-args "./bench.dhall" -vv
  - atspkg test --pkg-args "./bench.dhall" -vv
  - cabal new-build
  - cabal new-test
