---
resolver: nightly-2018-03-24
packages:
  - 'gmpint'
  - 'fast-arithmetic'
flags:
  ats-pkg:
    no-executable: true
extra-deps:
  - ats-pkg-2.8.0.0
  - composition-prelude-1.3.0.8
  - bzlib-0.5.0.5
  - cli-setup-0.2.0.2
  - dependency-0.1.0.10
  - dhall-1.12.0
  - shake-ats-1.5.0.11
  - shake-ext-2.8.0.0
  - hs2ats-0.2.1.9
  - language-ats-1.2.0.4;
  - casing-0.1.2.1
